quotes:
  edvanschleck:
    - "Sitzt du im Dreck, leck Ed v. Schleck."
    - "Ele, mele, schleck, Ed ist weg."
    - "Jetzt schleckst 13."
    - "Junge, Junge, hat der 'ne Zunge."
    - "Leck den Schleck weg."
    - "Die Zunge blecken und dann schlecken."
    - "Schleckern und kleckern, da kannste nicht meckern."
    - "Der SOmmer kommt, es wird jetzt warm, man trägt jetzt Ed v. Schleck im Arm."
    - "Ed v. Schleck, das ist 'nen toller Gag."
    - "Da schieb' ich nun, ich lieber Tor, und bin verschleckt wie nie zuvor!"
    - "Lieber schieben und schlecken als abwarten und Tee trinken."
    - "Schau mal wieder rein und schleck Dir ein!"
    - "Yeah-schieb-babaluba a schleck bäng-bu!"
    - "Erst leckste, dann schmeckste, dann schlürfste, dann schmatzte."
    - "Schieb dich frei, Schleck dich froh."
    - "Klicker-klacker-klecker, Ed v. Schleck ist lecker."