name: Build Maubot Plugin Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade maubot
    - name: Build Maubot Plugin Package
      run: |
        mbc build
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          *.mbp
